### ISSUE TITLE
Lacks E22_Man-Made_Object

### ISSUE THREAD

**Issue by cbutcosk** [american-art/ccma#1]
This preliminary modeling doesn't appear to model the collection's objects to E22_Man-Made_Object. If that stems from a problem in our submitted data, let me know and we can rectify and submit a PR.

**Comment by mayaram00** [comment]
The uploaded model was incomplete (and uploaded as a test) – I am currently working on finishing the mapping and will upload a final version soon. Sorry for the confusion!

**Comment by cbutcosk** [comment]
Great, I figured that might be the case--I'll close this issue then. Thanks for the update!
