### ISSUE TITLE
CCMA actor ID is missing

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/ccma#10]
http://data.americanartcollaborative.org/ccma/artist/uri/benjaminpaulakers
"_Artist_ID" : 8 is not mapped, but it's specified in [Preferred Identifier mapping](http://review.americanartcollaborative.org/entity/E39_Actor#field_8-search_0)

**Comment by bsnikhila** [comment]
Added it.
http://data.americanartcollaborative.org/page/ccma/constituent/8

**Comment by workergnome** [comment]
Confirmed.  Thanks.
