### ISSUE TITLE
department's P2_has_type; member of

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/ccma#11]
http://data.americanartcollaborative.org/page/ccma/thesauri/department/permanentcollection
- P2_has_type is correctly set to aat:300263534 "department", but should be URL not string
- `crm:P107i_is_current_or_former_member_of ?institution` is missing

See https://github.com/american-art/wam/issues/20 for appropriate URL to use  for `?institution`. In this case it should be http://data.americanartcollaborative.org/ccma

**Comment by bsnikhila** [comment]
Fixed the P2_has_type issue

**Comment by bsnikhila** [comment]
Added the institution too

**Comment by workergnome** [comment]
Confirmed.  Thank you.
