### ISSUE TITLE
Missing artists on Production events?

### ISSUE THREAD

**Issue by cbutcosk** [american-art/ccma#13]
Maybe I'm missing something due to LOD-brain right now, but are artist entities no longer connected to production events in the mapping? See the production event for Alex Katz's [Study for 'Swamp Maple'](http://data.americanartcollaborative.org/ccma/object/4204/production) or the event for Benjamin Akers's  [St. Elizabeth of Hungary](http://data.americanartcollaborative.org/ccma/object/4/production), which both have timespans but not actors.

**Comment by workergnome** [comment]
Yup.  That looks like a regression.  @bsnikhila, can you look into this?

**Comment by VladimirAlexiev** [comment]
Perhaps the reason is that object records don't have actor ID, but only actor name (defying any rule for relational design). I analyzed the data a bit:
```sh
$ jq -r '.objects[] | [.Disp_Maker_1, .embark_ID] | @tsv' ccma-objects_artists_exhibs.json |sort -t $'\t' -k1>ccma-objects.txt
$ jq -r '.artists[] | [.Display_Name, ._Artist_ID] | @tsv' ccma-objects_artists_exhibs.json |sort -t $'\t' -k1>ccma-artists.txt
$ cut -d $'\t' -f 1 ccma-artists.txt|uniq -d
Margaret Bourke-White
$ grep 'Margaret Bourke-White' ccma-artists.txt
Margaret Bourke-White   227
Margaret Bourke-White   228
```
But let's say that's the same person, just a duplicate record. Now let's see if each object's artist has a record.
```sh
$ jq -r '.objects[] | [.Disp_Maker_1] | @tsv' ccma-objects_artists_exhibs.json |sort|uniq>ccma-objects1.txt
$ jq -r '.artists[] | [.Display_Name] | @tsv' ccma-objects_artists_exhibs.json |sort>ccma-artists1.txt
$ comm -23 ccma-objects1.txt ccma-artists1.txt >  ccma-objects2.txt
$ wc -l ccma-objects1.txt ccma-objects2.txt
 1732 ccma-objects1.txt
 1406 ccma-objects2.txt
```
- object 6601 doesn't have any artist
- @cbutcosk : out of  1732 artists appearing in objects, there are no records for 1406 of these artists (the majority). Eg this one is missing "Viviano (Circle Of) Codazzi"

**Comment by VladimirAlexiev** [comment]
This said: @bsnikhila should still make Production/performed_by/Person where the Person will have just a name.
And about the first two examples: there are records for these artists:
```sh
$ egrep 'Akers|Katz' ccma-artists1.txt
Alex Katz
Benjamin Paul Akers
```

**Comment by cbutcosk** [comment]
Good catch, not sure how I missed that for so long--I'm pushing a template to our servers today that includes objects' related  _Artist_ID field, should have a fix committed soon.

**Comment by cbutcosk** [comment]
Resolved this issue on the source data side in today's commit.

**Comment by cbutcosk** [comment]
@bsnikhila This is almost set, looks like the `crm:P108i_was_produced_by` link outbound from an object's production should point to `http://data.americanartcollaborative.org/ccma/constituent/<artist_id>` instead of `http://data.americanartcollaborative.org/ccma/<artist_id>`

**Comment by bsnikhila** [comment]
Done.

**Comment by cbutcosk** [comment]
Awesome!
