### ISSUE TITLE
omit CCMA null dates

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/ccma#14]
I searched for CCMA objects with null dates. Used less instead of grep, so I could browse around:
```sh
less +/'_Dat.*""' ccma.json
```

Something very weird happens:
- some of these objects got no Production node. But they have an author (Disp_Maker_1, Sort_Artist), so they need such node, and link to the author!
http://data.americanartcollaborative.org/page/ccma/object/49
http://data.americanartcollaborative.org/page/ccma/object/50
http://data.americanartcollaborative.org/page/ccma/object/229
- others have a timespan with some dates made out of thin air:
http://data.americanartcollaborative.org/page/ccma/object/62/production/timespan: 1873-74
http://data.americanartcollaborative.org/page/ccma/object/109/production/timespan: 1874-75

**Comment by cbutcosk** [comment]
Yeah I noticed that too in #13 -- constituents exist (eg, http://data.americanartcollaborative.org/ccma/constituent/451) but AFAICT no productions links to their constituents.

I think the second group are pulling their data from "Disp_Create_DT", a charmingly-named Embark/4D macro that emits a combo of start/end dates or its own separate string.

**Comment by bsnikhila** [comment]
It turns out the 3 objects mentioned above, 49, 50 and 229, have artist IDs associated with them 934, 1098 and 1741 respectively. But none of these IDs exist in the constituents data. So they appear like zombies.

For the timespan, I modified the model such that only if the object has entries in either the Disp_Start_Dat or Disp_End_Date, then the timespan URI is generated.

**Comment by cbutcosk** [comment]
Woah, looks like I made a bad assumption somewhere about our artist data. I'll dig into this next week and post under #25 for it. @VladimirAlexiev are you good on the dates in this issue?

**Comment by VladimirAlexiev** [comment]
The dates seem ok. #25 is more serious
