### ISSUE TITLE
xsd:date for CCMA dates

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/ccma#15]
Some stats on CCMA dates. Replaced every digit with `D` to see the patterns:
```sh
perl -ne 's{.*_Dat.*"(.*)".*}{$1} and do {s{\d}{D}g; print}' ccma.json|sort|uniq -c
   3730
      4 D
      1 D BCE
      2 D/DDDD
      5 DD
      3 DD BCE
      1 DD,DDD
    186 DDD
    238 DDD BCE
  12194 DDDD
     20 DDDD BCE
```
- As you can see, the majority (12k) are plain 4-digit dates. Please make them out as xsd:date as done for other collections (eg http://data.americanartcollaborative.org/page/npg/object/4/production/timespan). P82a should be completed to `yyyy-01-01` and P82b to `yyyy-12-31`
- there are 3.7k null dates, see https://github.com/american-art/ccma/issues/14
- could you also handle BCE dates? In XSD these should be formatted as -0DDD, -DDDD, -DDDDD (i.e. minimum 4 digits)

**Comment by bsnikhila** [comment]
I have modified all dates to the xsd:date format.
