### ISSUE TITLE
Same actor, different ID

### ISSUE THREAD

**Issue by bsnikhila** [american-art/ccma#16]
There seems to be one actor, "Margaret Bourke-White", that has 2 Artist IDs: 227 and 228

**Comment by cbutcosk** [comment]
Ah, yeah that's bad data on our end--we'll fix that in an upcoming commit.

**Comment by cbutcosk** [comment]
The commit I just made fixes this issue, we can close it the next time the mapping runs.

**Comment by bsnikhila** [comment]
Seems fine.
