### ISSUE TITLE
omit CCMA actor null dates

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/ccma#17]
http://data.americanartcollaborative.org/page/ccma/constituent/451 has http://data.americanartcollaborative.org/page/ccma/constituent/451/birth but no useful data in that Birth.

If he's got a birth date, emit it. Else skip the Birth.
Same for Death

**Comment by bsnikhila** [comment]
It has the birth date as 1931

**Comment by VladimirAlexiev** [comment]
Checked for Birth/Death without timespan http://yasgui.org/short/SJkXZbY3e
```sparql
SELECT *  {
  {?x a crm:E67_Birth} union {?x a crm:E69_Death}
  filter not exists {?x crm:P4_has_time-span ?y}
}
```
No results.

Checked for timespans without class http://yasgui.org/short/rJfob-t3l
```sparql
SELECT *  {
  ?x crm:P4_has_time-span ?y
  filter not exists {?y a crm:E52_Time-Span}
}
```
No results.

Checked for timespan without dates http://yasgui.org/short/r1_Ixbthg:
```sparql
select * {
  ?x a crm:E52_Time-Span.
  filter not exists {?x crm:P82a_begin_of_the_begin ?y}
  filter not exists {?x crm:P82_at_some_time_within ?y}
  filter regex(str(?x),"ccma")
}
```
Finds 88 CCMA URLs, but they are all object production (not agent birth) and they got rdfs:label showing a variety of dates, so not easy to parse.

Think we can close this, thanks!
