### ISSUE TITLE
datatype for CCMA actors

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/ccma#18]
Since all Date_Disp for CCMA actors are years, emit a datatype.
- it's easier to just tack xsd:gYear
- if you want to use xsd:date (cc @workergnome), you have to complete it differently.
eg for http://data.americanartcollaborative.org/page/ccma/constituent/20/birth/date
```ttl
crm:P82a_begin_of_the_begin	"1859-01-01"^^xsd:date
crm:P82b_end_of_the_end	"1859-12-31"^^xsd:date
```

**Comment by workergnome** [comment]
I'd strongly prefer`xsd:date` for all dates—otherwise, I'm going to have to do the conversion on my end to compare across institutions (since some have fuller data).

**Comment by bsnikhila** [comment]
Changed it to xsd:date.

**Comment by VladimirAlexiev** [comment]
http://data.americanartcollaborative.org/page/autry/maker/readthomasbuchanan/death_timespan says `crm:P82a_begin_of_the_begin "1872-1-1"^^xsd:date`.
But XSD demands you spell it "1872-01-01" (yyyy-mm-dd)

**Comment by cbutcosk** [comment]
This looks fixed to me, including the `1872-01-01` that Vladimir raises. Closing this, but feel free to re-open.
