### ISSUE TITLE
CCMA object ID missing

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/ccma#19]
CCMA object IDs are not mapped, eg
http://data.americanartcollaborative.org/page/ccma/object/4, http://data.americanartcollaborative.org/page/ccma/object/5.
[See mapping](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_25-search_0)  (P1_is_identified_by...).  Click on "Turtle" because @workergnome the image is broken

**Comment by bsnikhila** [comment]
Added.

**Comment by workergnome** [comment]
👍
