### ISSUE TITLE
Materials have multiple labels

### ISSUE THREAD

**Issue by workergnome** [american-art/ccma#23]
See, for instance: http://data.americanartcollaborative.org/page/ccma/thesauri/material/ink

`ink` and `Ink` are both listed.

**Comment by cbutcosk** [comment]
http://data.americanartcollaborative.org/page/ccma/thesauri/material/lithograph has this too: `Lithograph` x 3 and `Lithograph?`. `Lithograph?` (ie, looks like litho but we're not sure) might want to be a different url than `Lithograph`, though.

**Comment by workergnome** [comment]
Yeah—I think part of this is data issues in the source data, and part of is is URL smushing.

**Comment by cbutcosk** [comment]
Yeah this is reminding me to normalize that field and Support--lots of no-caps weirdness there. Only one object with "Lithograph?" at least.

**Comment by bsnikhila** [comment]
I converted them all to lower case and removed extra spaces for now.

**Comment by cbutcosk** [comment]
Cool, and I stripped the question marks out of our JSON and would call this good for now. Next time the mapping runs we can close this.

That field has a lot of cruft--edition, some printer/publisher info, in addition to the actual material composition--so I'm reticent to do much more cleaning here. Definitely a case for a materials parser and a way to express uncertainty about composition.

**Comment by bsnikhila** [comment]
Should be fine now.
