### ISSUE TITLE
CCMA missing authors

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/ccma#25]
@cbutcosk: @bsnikhila wrote: "It turns out the 3 objects mentioned above, 49, 50 and 229, have artist IDs associated with them 934, 1098 and 1741 respectively. But none of these IDs exist in the constituents data. So they appear like zombies."

We need those authors. I compared distinct Artist_ID's present in ccma-artists and ccma-objects (see https://gist.github.com/VladimirAlexiev/dc6e07917b21efd1a4ba92e443f8bae9):
- 1736 in objects (ccma_obj-artists-id.txt)
- 338 in artists (ccma_artists-id.txt)
- 11 only in artists but not in objects (ccma-artists-notNeeded.txt)
- 1409 in objects but not in artists (ccma-artists-missing.txt)
- 327 in both

**Comment by cbutcosk** [comment]
Tracked down this bug today, should have a fix in the next day or two.

**Comment by cbutcosk** [comment]
OK, so the most recent commit should resolve the source data side of our zombie constituents 🎉

**Comment by cbutcosk** [comment]
@caknoblock @bsnikhila Can one of you do another mapping run to get this data into the triplestore? I'm blocked on completing artist curation until it's there and the difference is substantial (~200 artists to ~1400+).
