### ISSUE TITLE
Map "Description" field

### ISSUE THREAD

**Issue by cbutcosk** [american-art/ccma#29]
My most recent commit adds a `Description` field for objects. This should be mapped like `Main Description` in the target mapping.

@workergnome Do you have a pref/is there consensus on how to pass line breaks for that field? Use a `<p>`? We have a few long descriptions..

**Comment by workergnome** [comment]
If you embed HTML, we'll emit it.  I _believe_ that if you include newlines, we'll convert them to `<br/>` for display in Browse.

**Comment by cbutcosk** [comment]
Doh, just noticed this never actually made it into that commit, should show up in the data now.

`<br/>` it is!
