### ISSUE TITLE
Main Description has no rdf:value but 2 URIs

### ISSUE THREAD

**Issue by cbutcosk** [american-art/ccma#31]
In the mapping of `Main Description`, the string that should be rdf:value is mapped as the `Linguistic_Object`'s URI, in addition to its actual URI.

That extra-long URI may be why the CCMA's object triples got zapped in the ISI triplestore after the models were applied last night.

**Comment by bsnikhila** [comment]
Fixed it.

**Comment by cbutcosk** [comment]
Awesome, thanks!
