### ISSUE TITLE
don't use blank nodes

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/ccma#6]
http://data.americanartcollaborative.org/page/ccma/object/4 has crm:P45_consists_of a blank node.
Blank nodes are hard to work with and to update.
So don't use blank nodes

**Comment by bsnikhila** [comment]
Fixed it

**Comment by workergnome** [comment]
Looks fixed to me.

**Comment by VladimirAlexiev** [comment]
(!) in the title means that the bug (potentially) applies to many museums.
Trying to check: https://github.com/american-art/semantic-hosting/issues/8
