### ISSUE TITLE
(!) website mapping should have actual URL

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/ccma#7]
http://data.americanartcollaborative.org/ccma/object/4:
```ttl
<http://data.americanartcollaborative.org/ccma/object/4>
   foaf:homepage <http://data.americanartcollaborative.org/ccma/object/4/url>.
<http://data.americanartcollaborative.org/ccma/object/4/url> rdf:type foaf:Document;
  rdfs:label "http://embark.colby.edu/Obj4".
```
See the [Primary Website mapping](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_28-search_0): it wants the actual website URL in the first place, and a label in the second. @workergnome confirm.

So there are two bugs:
- foaf:homepage should be the actual webpage URL
- the webpage should be a resource, not a string

So it should be:
```ttl
<http://data.americanartcollaborative.org/ccma/object/4>
   foaf:homepage <http://embark.colby.edu/Obj4>.
<http://embark.colby.edu/Obj4> rdf:type foaf:Document;
  rdfs:label "Object 4: St. Elizabeth of Hungary". # or whatever
```

**Comment by workergnome** [comment]
I confirm @VladimirAlexiev interpretation of this.  That's the intent of the mapping.

**Comment by bsnikhila** [comment]
Fixed it.

**Comment by workergnome** [comment]
Thank you.

**Comment by VladimirAlexiev** [comment]
It still has `rdfs:label "http://embark.colby.edu/Obj4"`, see http://yasgui.org/short/HJzV-ol2e.
But I suppose @workergnome doesn't use that label anyway and hardcodes "website" or something.

**Comment by workergnome** [comment]
Descriptive labels are always great, but I'll take what I can get.   Or nothing, as the case may be.  

(in the browse app, I'm likely to have a field label, such as "Website", and use the `rdfs:label` as the hyperlink text for the URI.)
