### ISSUE TITLE
broken image URLs in source data

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/ccma#8]
https://github.com/american-art/PUAM/issues/36 wonders about an image URL (http://embark.colby.edu:8080/images/2013.003_001_cd.jpg ).
https://github.com/american-art/aac_mappings/issues/51 shows that is the image URL in the source.
However, Colby's site returns 404 not found

**Comment by cbutcosk** [comment]
Yep, we're working on that--that field will be fixed in our next commit.

**Comment by cbutcosk** [comment]
Just finished fixing this in our data and server-side. Next time @sjayakum or @mit2nil run the mapping we can close this.

**Comment by bsnikhila** [comment]
Done.

**Comment by VladimirAlexiev** [comment]
Checked http://data.americanartcollaborative.org/puam/object/38930

**Comment by VladimirAlexiev** [comment]
The issue is solved for PUAM but not for CCMA, eg see http://data.americanartcollaborative.org/page/ccma/object/4.  But i'll open another one for this
