### ISSUE TITLE
CCMA name part mapping is screwed

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/ccma#9]
http://data.americanartcollaborative.org/page/ccma/thesauri/last_name/akers
You've mixed together the data about the name "Akers" and its type aat:300404652 "last name"

**Comment by VladimirAlexiev** [comment]
So the crm:P2_has_type link is a loop

**Comment by bsnikhila** [comment]
http://data.americanartcollaborative.org/page/ccma/constituent/8
Should be fixed.

**Comment by workergnome** [comment]
Closer, but there shouldn't be two name types:

<http://data.americanartcollaborative.org/ccma/constituent/8/name>
<http://data.americanartcollaborative.org/ccma/constituent/8/name_composition>
are both the same thing—it's just that the name, **Benjamin Paul Akers**, consists of "Benjamin" and "Akers".

**Comment by bsnikhila** [comment]
Fixed it.

**Comment by workergnome** [comment]
Confirmed.
